<?php
$xml=new DOMDocument("1.0");
$xml_livraria=$xml->createElement("Livraria");
	$xml_livro=$xml->createElement("Livro");
			$xml_isbn=$xml->createElement("isbn","1");
			$xml_titulo=$xml->createElement("titulo","Assasinato no expresso oriente");
		$xml_genero=$xml->createElement("genero");
			$xml_descricao=$xml->createElement("descricao","Ficcao policial");
			$xml_genero->appendChild($xml_descricao);
			$xml_descricao=$xml->createElement("descricao","Suspense");
		$xml_autor=$xml->createElement("autor","Aghata Cristie");
		$xml_publicacao=$xml->createElement("xml_publicacao","1934");
$xml_genero->appendChild($xml_descricao);
$xml_livro->appendChild($xml_titulo);
$xml_livro->appendChild($xml_isbn);
$xml_livro->appendChild($xml_genero);
$xml_livro->appendChild($xml_autor);
$xml_livro->appendChild($xml_publicacao);
$xml_livraria->appendChild($xml_livro);
	$xml_livro=$xml->createElement("livro");
			$xml_isbn=$xml->createElement("isbn","2");
			$xml_titulo=$xml->createElement("titulo","O codigo da vince");
			$xml_genero=$xml->createElement("genero");
				$xml_descricao=$xml->createElement("descricao", "ficcao policial");
				$xml_genero->appendChild($xml_descricao);
				$xml_descricao=$xml->createElement("descricao","suspense");
			$xml_autor=$xml->createElement("autor","Dan brown");
			$xml_publicacao=$xml->createElement("publicacao","2003");
$xml_genero->appendChild($xml_descricao);
$xml_livro->appendChild($xml_isbn);
$xml_livro->appendChild($xml_titulo);
$xml_livro->appendChild($xml_genero);
$xml_livro->appendChild($xml_autor);
$xml_livro->appendChild($xml_publicacao);
$xml_livraria->appendChild($xml_livro);
	$xml_livro=$xml->createElement("livro");
		$xml_isbn=$xml->createElement("isbn","2");
		$xml_titulo=$xml->createElement("titulo","cabana");
		$xml_genero=$xml->createElement("genero");
			$xml_descricao=$xml->createElement("descricao","ficcao");
		$xml_autor=$xml->createElement("Autor","William P.young");
		$xml_publicação=$xml->createElement("Publicação");
$xml_livro->appendChild($xml_isbn);
$xml_livro->appendChild($xml_titulo);
$xml_genero->appendChild($xml_descricao);
$xml_livro->appendChild($xml_genero);
$xml_livro->appendChild($xml_autor);
$xml_livro->appendChild($xml_publicacao);
$xml_livraria->appendChild($xml_livro);
	$xml_livro=$xml->createElement("livro");
		$xml_isbn=$xml->createElement("isbn","4");
		$xml_titulo=$xml->createElement("titulo","o pequeno principe");
		$xml_genero=$xml->createElement("genero");
			$xml_descricao=$xml->createElement("descricao","ficcao");
			$xml_genero->appendChild($xml_descricao);
			$xml_descricao=$xml->createElement("descricao","fabula");
			$xml_genero->appendChild($xml_descricao);
			$xml_descricao=$xml->createElement("descricao","literatura infantil");
		$xml_autor=$xml->createElement("autor","Antoine");
		$xml_publicacao=$xml->createElement("publicacao","1943");
$xml_livro->appendChild($xml_isbn);
$xml_livro->appendChild($xml_titulo);
$xml_livro->appendChild($xml_genero);
$xml_livro->appendChild($xml_autor);
$xml_livro->appendChild($xml_publicacao);
$xml_livraria->appendChild($xml_livro);
$xml->appendChild($xml_livraria);
$xml->save("livraria.xml");


?>